frontpage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='front-index'),
    path('article/<slug:title>', views.article, name='article')
    ]

nkrsiSystem/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from nkrsiSystem import settings
bbbbbbbba
urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('internal/', include('usersystem.urls')),
    path('internal/', include('internalsystem.urls')),
    path('internal/', include('resource_monitoring.urls')),
    path('', include('frontpage.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

frontpage/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _


class FrontPage(models.Model):
    order = models.IntegerField(_('order'), default=0,
                                help_text=_('Order in which links will be presented on home page. '
                                            'The lower number the higher position.'))
    title = models.CharField(_('title'), max_length=200)
    slug = models.SlugField(unique=True)
    text = models.TextField(_('text'))

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(FrontPage, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _('front subpage')
        verbose_name_plural = _('front subpages')

    def __str__(self):
        return self.title


class FrontPageImage(models.Model):
    order = models.IntegerField(_('order'), default=0,
                                help_text=_('Order in which links will be presented on home page. '
                                            'The lower number the higher position.'))
    text = models.TextField(_('text'))
    img = models.ImageField(_('image'))
    page = models.ForeignKey(FrontPage, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('front subpage image')
        verbose_name_plural = _('front subpage images')

frontpage/views.py
from django.shortcuts import render

from frontpage.models import FrontPage


def index(request):
    args = dict()
    args['pages'] = FrontPage.objects.all()
    return render(request, 'front_page/main.html', args)


def article(request, title):
    args = dict()
    args['pages'] = FrontPage.objects.all()
    args['article'] = FrontPage.objects.get(slug=title)
    return render(request, 'front_page/page.html', args)

templates/front_page/base.html
{% extends 'bootstrap4/bootstrap4.html' %}
{% load bootstrap4 static i18n %}
{% block bootstrap4_extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static "frontpage.css" %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    {% block extra_head %}{% endblock %}
{% endblock %}
{% block bootstrap4_title %}Strona Naukowego Koła Robotyki i Sztucznej Inteligencji UJ{% endblock %}
{% block bootstrap4_content %}
    <nav class="navbar navbar-expand-md navbar-dark fixed-top navbar-red">
        <a class="navbar-brand" href="{% url 'front-index' %}">NKRSI</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                {% if not request.user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'login' %}">{% trans 'Log in' %}</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'index' %}">{% trans 'Internal system' %}</a>
                    </li>
                {% endif %}
            {% for page in pages %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'article' title=page.slug %}">{{ page.title }}</a>
                </li>
            {% endfor %}

            </ul>
        </div>
    </nav>
    {% block main_cointainer %}
        <div class="container content">
            {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}
            {% block content %}(no content){% endblock %}
        </div>
    {% endblock %}
{% endblock %}

templates/front_page/main.html
{% extends 'front_page/base.html' %}
{% load static i18n %}
{% block main_cointainer %}
    <div id="carouselNKRSI" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselNKRSI" data-slide-to="0" class="active"></li>
            <li data-target="#carouselNKRSI" data-slide-to="1"></li>
{#            <li data-target="#carouselNKRSI" data-slide-to="2"></li>#}
        </ol>
        <div class="carousel-inner" style="height: 20em">
            <div class="carousel-item active">
                <img src="{% static 'logo.svg' %}" class="carousel-img" alt="...">
                <div class="carousel-caption">
                    <p>Witaj na stronie Naukowego Koła Robotyki i Sztucznej Inteligencji UJ.</p>
                </div>
            </div>
            <div class="carousel-item">
                <a href="https://www.facebook.com/nkrsiuj/">
                    <img src="{% static 'facebook.png' %}" class="carousel-img" alt="...">
                    <div class="carousel-caption">
                        <p>Odwiedź nas na Facebooku.</p>
                    </div>
                </a>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselNKRSI" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselNKRSI" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="container content">
        <div class="jumbotron">
            <h3 class="display-5">Aktualności z Facebooka!</h3>
            <p class="lead">{{ fb_news_text }}</p>
            <p>{{ fb_news_date }}</p>
            <p class="lead">
                <a class="btn btn-primary btn-lg" href="https://www.facebook.com/nkrsiuj/" role="button">
                    Przejdź do aktualności</a>
            </p>
        </div>

        <div class="jumbotron">
            <div class="row">
                <div class="col-md-6 map-col">
                    <div id="map"></div>
                </div>
                <div class="col-md-6">
                    Siedziba Naukowego Koła Robotyki i Sztucznej Inteligencji<br>
                    Wydział Matematyki i Informatyki Uniwersytetu Jagiellońskiego<br>
                    Pokoje: 1164, 1162<br>
                    ul. Stanisława Łojasiewicza 6<br>
                    30-348 Kraków<br>
                    E-mail: <a href="mailto:nkrsi@uj.edu.pl">nkrsi@uj.edu.pl</a><br>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}
{% block bootstrap4_extra_script %}
    <script>
        function initMap() {
            var wmii = {lat: 50.030521, lng: 19.906964};
            var map = new google.maps.Map(
                document.getElementById('map'), {zoom: 15, center: wmii});
            var marker = new google.maps.Marker({position: wmii, map: map});
        }
    </script>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBEL1eAXRFWmU2wJnwvUzXpR3pZzev_r40&callback=initMap">
    </script>
{% endblock %}

templates/front_page/page.html
{% extends 'front_page/base.html' %}
{% load static i18n %}
{% block main_cointainer %}

    <div class="container content">
        <div class="jumbotron">
            <h3 class="display-5">{{ article.title }}</h3>
            <p class="lead">
                {{ article.text|safe }}
            </p>
            <div class="container">

                {% for image in article.frontpageimage_set.all %}
                    <div class="row">

                        {% if forloop.counter|divisibleby:2 %}
                            <div class="col-lg-4">
                                <img src="{% get_media_prefix %}{{ image.img }}" class="img-thumbnail">
                            </div>
                            <div class="col-lg-8 align-self-center">{{ image.text|safe }}</div>

                        {% else %}
                            <div class="col-lg-8 align-self-center">{{ image.text|safe }}</div>
                            <div class="col-lg-4 order-first order-lg-last">
                                <img src="{% get_media_prefix %}{{ image.img }}" class="img-thumbnail">
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}